# Generated by CodiumAI
from typing import Any, Self
from unittest.mock import create_autospec, patch

import pytest

from src.click_opt.cli_options import CliOptions
from src.elastic import ElasticsearchClient
from src.esxport import EsXport


@patch("src.esxport.EsXport._validate_fields")
class TestExport:
    """Tests that the method exports the data with valid arguments."""

    out_file = "_export.csv"

    csv_header = ["age", "name"]

    def test_export_with_valid_arguments(
        self: Self,
        _: Any,
        mock_es_client: ElasticsearchClient,
        cli_options: CliOptions,
    ) -> None:
        """Checks if the method exports the data properly when given valid arguments."""
        export = create_autospec(EsXport(cli_options, mock_es_client).export)

        export()

        export.assert_called_once_with()

    def test_export_invalid_format(
        self: Self,
        _: Any,
        mock_es_client: ElasticsearchClient,
        cli_options: CliOptions,
    ) -> None:
        """Check if exception is raised when formatting is invalid."""
        cli_options.format = "invalid_format"
        with patch.object(EsXport, "_extract_headers", return_value=[]), pytest.raises(NotImplementedError):
            EsXport(cli_options, mock_es_client).export()
