"""Common used strings."""
index_not_found = "Any of index(es) {} does not exist in {}."
using_indexes = "Using indices: {indexes}."
using_query = "Using query: {query}."
output_fields = "Output fields : {fields}."
sorting_by = "Sorting by: {sort}."
