name: GitHub Workflow Cleanup

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  cleanup:
    name: GitHub Cleanup
    uses: nikhilbadyal/ghactions/.github/workflows/github-workflow-cleaner.yml@340a2a7533136b52262974e073716c2400c797cb # main
    secrets:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
