name: GitHub Workflow Cleanup

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  cleanup:
    name: GitHub Cleanup
    uses: nikhilbadyal/ghactions/.github/workflows/github-workflow-cleaner.yml@7ad61597236c9f945c6a25d16685d812830853fe # main
    secrets:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
