name: Unit Pytest & Sonar Analysis
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  tests:
    name: >-
      Pytest - Python ${{ matrix.PYTHON_VERSION }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { PYTHON_VERSION: '3.10' }
          - { PYTHON_VERSION: '3.11' }
          - { PYTHON_VERSION: '3.12', GENERATE_COVERAGE: 'true' }
          - { PYTHON_VERSION: '3.13' }
          - { PYTHON_VERSION: '3.14' }
    steps:
      - name: "Checkout to repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Setup Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          cache: 'pip'
          allow-prereleases: true

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.dev.txt

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: "Run tests"
        uses: pavelzw/pytest-action@510c5e90c360a185039bea56ce8b3e7e51a16507 # v2.2.0

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Test reporter
        uses: phoenix-actions/test-reporting@f957cd93fc2d848d556fa0d03c57bc79127b6b5e # v15
        if: always()
        with:
          name: EsXport tests for (Python ${{ matrix.PYTHON_VERSION }})
          path: junit.xml
          reporter: java-junit
          output-to: step-summary
          only-summary: true
          max-annotations: 0

      - name: Upload coverage report for SonarQube
        if: matrix.GENERATE_COVERAGE == 'true'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 1

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    steps:
      - name: "Checkout to repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
