name: Release on Version Bump

on:
  push:
    branches: [main]
    paths:
      - 'esxport/__init__.py'
      - 'pyproject.toml'

jobs:
  auto-tag:
    if: contains(github.event.head_commit.message, '⬆️ Bump to') && !startsWith(github.event.head_commit.message, 'Merge')
    runs-on: ubuntu-latest
    outputs:
      tag-created: ${{ steps.check_tag.outputs.tag-created }}
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Extract version from __init__.py
        id: get_version
        run: |
          VERSION=$(python -c "import esxport; print(esxport.__version__)")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse --verify "refs/tags/v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "tag-created=false" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "tag-created=true" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ steps.get_version.outputs.version }}" -m "Release v${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"

      - name: Create GitHub Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          body: |
            ## Release v${{ steps.get_version.outputs.version }}

            ### Changes
            - Updated to Elasticsearch ${{ steps.get_version.outputs.version }}
            - Compatibility verified with latest Elasticsearch features

            ### Installation
            ```bash
            pip install esxport==${{ steps.get_version.outputs.version }}
            ```

            ### Full Changelog
            See the [commit history](https://github.com/${{ github.repository }}/commits/v${{ steps.get_version.outputs.version }}) for detailed changes.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: auto-tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Clean previous builds
        run: |
          rm -rf dist/

      - name: Build package with hatch
        run: |
          hatch build

      - name: Verify package contents
        run: |
          ls -la dist/
          # Verify both wheel and sdist are created
          test -f dist/*.whl
          test -f dist/*.tar.gz

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: dist/

  publish-pypi:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
